[earthengine]
type = "service_account"
project_id = "ee-victoridakwo"
private_key_id = "9cfb0950436b25d51f238ebcb5e1040ee9ab5db3"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDnMR7Cvp6F3Upa
fuM2poleICJxnJTZ/f8n5jWfYJGMOfJNgez/eSJWub4UVxZtdyp6SlfwtqnM93By
tkv+ZaFDOCUoXmsMtFqBJ5H3TaaMtnXXPpdx19v1g5VDXQn9J5yYm7eBtobbQOqr
K41eMuP9xwgO9dbujLH14BwV2XvKnZPQw6xc3LhCpcS1a3x9KM31qqVsLiwtfP2+
swKPh9lDC8mOc1nKpWwOsi0XIBUacD3Pe7VJsGUawEu261MApFd7h7piDseuqPx4
fbIFUiVDIaRpqGZRoIgl9Avd+vV5Foue2rYSxfFyTXi3+mqsyo8AtYxG7vcQ6+Lv
elZWrh81AgMBAAECggEAT15ipBLS0zwUQZscH+/uatz3Vi+ePnRfe3Ah6pQ5g32F
PKylE1OfwUxFADChp3TopVEOfboH8zDjbs48qppzUWNeBkzbzWHBTGOsTc1fpyEg
tYNsdI3ZmqDQxm6TdlB6Bz42MpbaFz1jEt6BytwHv2Dr2E73ua+djL6ihbHDONxX
DYRPQY1235cqOgRBpkMvzPutnxWqBB5DKXT8RLeKfsNdul2IOyI9Nn5o94X1hpl5
I0QZiZrA3ayoISMKOCHW8zqp/NIXnGy2zarKmKnNPp/4gukZQ93tNdI6xXEerNbO
53zBuYSu2ZNgV54XS8Cj44el7ruJaB5lXZkQFuQxJQKBgQD1pulb/QKQaQzXyW6B
eFpyy/HlzmQQbzQDTfkTROLlVIZUMeHcgFlF3TITlSMSZDY2evRflQrVbZRaVcSl
aqe4cNYARbHrF8LBX3cLHbaRNKa3lvC5iJPOzq/7o5hhl+wAdrbwhxa7LKr/3rQi
ID6KZGnVHvSA6S99tlUmh9C01wKBgQDw7kWgCQzoynmmDknJqk4ZcKjqGB05wBRl
Y1UXleE1t634jmb5Lkddymrczi2bT54JDSCRgHxAseYpf+HEYtFn1WQxYkI1dZdm
RiU+w/dm8rzK3DvyC5xIbPh7akzd1r/i79gGJf334ca5ZdZA+Q0NRHjZDDitKWko
YjRhXGs+0wKBgCCyRa9Dvtqf0ODL49SBw3AyKxFOZk01r/OcpkFlUtn5ZSPBu/FQ
eBFvfqHSoOdqxTh9Jxety9JakntvnQvzZT2Mbz98B1FmSTrZzQuCufEb0/Dtuz7G
qf3FzvCsdrTOts/c/T6IjIL/UAdcihdcuVZMRTXjt+GMqBCQe0b0ntfjAoGARIs1
Sbtpbc004LZN7c7C21/+3mKv5d8srk+dRNGCOfsgxocU6q1s5lURI/KQbRAwoNiY
PGz2bJ1wIrxcKbgHZWgDUj1nIrhqs1EfhYTRHPvQFFKlx03gT4aZBtuONMrE2rZr
mgwy/dPA6rv7QY7ZVL33N6DPeww9+5w81LorVLsCgYEAnKgIcvQl011PS3xMSFS5
DleVtxJ0jIQNPU5NX/xBgbESCtXB/E474y7USPLc8cYc8xPhgiS9Aa0OVyfP0gxl
SsEONS5r3aAw2ym2UZnAwKavQfOR3T1wkP/mmJZXbbG5x3/tUL4NGCMf/vQraX0/
VZAscmLkFFDhieJWtXaoEa8=
-----END PRIVATE KEY-----
"""
client_email = "heatindex-analytics@ee-victoridakwo.iam.gserviceaccount.com"
client_id = "102740711274882741563"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/heatindex-analytics%40ee-victoridakwo.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
